/**
 * Standard error codes returned by this service.
 * Matches the contract in docs/api-contract.md.
 */
export const ERROR_CODES = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  EMAIL_SERVICE_NOT_CONFIGURED: 'EMAIL_SERVICE_NOT_CONFIGURED',
  EMAIL_SEND_FAILED: 'EMAIL_SEND_FAILED',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  UNSUPPORTED_FILE_TYPE: 'UNSUPPORTED_FILE_TYPE',
  CV_PARSE_FAILED: 'CV_PARSE_FAILED',
  PDF_RENDERER_UNAVAILABLE: 'PDF_RENDERER_UNAVAILABLE',
  CV_UPLOAD_QUOTA_EXCEEDED: 'CV_UPLOAD_QUOTA_EXCEEDED',
  CV_ANALYSIS_DAILY_LIMIT_REACHED: 'CV_ANALYSIS_DAILY_LIMIT_REACHED',
  FEATURE_NOT_INCLUDED: 'FEATURE_NOT_INCLUDED',
  FEATURE_USAGE_LIMIT_REACHED: 'FEATURE_USAGE_LIMIT_REACHED',
  PAYMENT_ORDER_NOT_FOUND: 'PAYMENT_ORDER_NOT_FOUND',
  PAYMENT_PROVIDER_ERROR: 'PAYMENT_PROVIDER_ERROR',
  PAYMENT_WEBHOOK_INVALID: 'PAYMENT_WEBHOOK_INVALID',
  AI_SERVICE_UNAVAILABLE: 'AI_SERVICE_UNAVAILABLE',
  AI_ANALYSIS_FAILED: 'AI_ANALYSIS_FAILED',
  INTERVIEW_TIME_LIMIT_REACHED: 'INTERVIEW_TIME_LIMIT_REACHED',
  PROMPT_TEMPLATE_NOT_FOUND: 'PROMPT_TEMPLATE_NOT_FOUND',
  EMBEDDING_FAILED: 'EMBEDDING_FAILED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
